DROP TABLE students CASCADE;
CREATE TABLE students(
std_id SERIAL,
std_name VARCHAR(30),
crs_id INT REFERENCES courses(crs_id),
PRIMARY KEY(std_id)
);
CREATE TABLE courses (
    crs_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 100),
    crs_name VARCHAR(30),
    PRIMARY KEY (crs_id)
);
INSERT INTO students (std_name,crs_id)
VALUES ('Rory',100), ('Kirk',102),('Taylor',101),('Patty',103),('Babette',NULL);




INSERT INTO courses (crs_name)
VALUES('Tamil'),('English'),('Maths'),('Science');

SELECT * FROM students;
SELECT * FROM courses;

--can 2 students study same course? why,yes
INSERT INTO students (std_name,crs_id)
VALUES ('Lorelai',100);

SELECT s.std_id, s.std_name, c.crs_name
FROM students s JOIN courses c
ON s.crs_id = c.crs_id;

SELECT s.std_id, s.std_name, c.crs_name
FROM students s INNER JOIN courses c
ON s.crs_id = c.crs_id;


SELECT s.std_id, s.std_name, c.crs_name
FROM students s  LEFT JOIN courses c
ON s.crs_id = c.crs_id;

INSERT INTO courses (crs_name)
VALUES('Drama');

SELECT s.std_id, s.std_name, c.crs_name
FROM students s RIGHT JOIN courses c
ON s.crs_id = c.crs_id;

SELECT s.std_id, s.std_name, c.crs_name
FROM students s FULL OUTER JOIN courses c
ON s.crs_id = c.crs_id;

SELECT s.std_id, s.std_name, c.crs_name
FROM students s CROSS JOIN courses c;

SELECT s.std_id, s.std_name, c.crs_name
FROM students s NATURAL JOIN courses c;

--self join
DROP TABLE study_group CASCADE;
CREATE TABLE study_group( 
	std_id INT,
	std_name VARCHAR(30),
	mentor_id INT);
INSERT INTO study_group (std_id,std_name, mentor_id) VALUES
(1,'Luke',2),(2,'Taylor',NULL),(3,'Jess',4),(4,'Rory',1);
SELECT * FROM study_group;
SELECT st.std_id, st.std_name AS student, mt.std_name AS mentor
FROM study_group st LEFT JOIN study_group mt
ON st.mentor_id=mt.std_id;

LEFT SEMI JOIN

SELECT * FROM students s
WHERE EXISTS(
	SELECT 1 FROM courses c
	WHERE s.crs_id = c.crs_id);

SELECT s.* FROM students s
WHERE s.crs_id IN(
SELECT crs_id FROM courses);

SELECT * FROM students s
WHERE NOT EXISTS(
	SELECT 1 FROM courses c
	WHERE s.crs_id = c.crs_id);

SELECT * FROM students s LEFT JOIN courses c
ON s.crs_id = c.crs_id
WHERE s.crs_id IS NULL;

--set operators
SELECT crs_id FROM students WHERE std_name='Patty'
UNION
SELECT crs_id FROM courses WHERE crs_name='Drama';

SELECT crs_id FROM students WHERE std_name='Kirk'
INTERSECT
SELECT crs_id FROM courses WHERE crs_name='English'; 
--kirk doesn't study english

SELECT crs_id FROM students WHERE std_name='Kirk'
EXCEPT
SELECT crs_id FROM courses WHERE crs_name='Maths';
--kirk doesn't study maths







