DROP TABLE IF EXISTS dim_product CASCADE;
DROP TABLE IF EXISTS dim_customer CASCADE;
DROP TABLE IF EXISTS dim_date CASCADE;
DROP TABLE IF EXISTS sales_fact CASCADE;
CREATE TABLE dim_product (
 product_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_name VARCHAR(50),
 category VARCHAR(30),
 price DECIMAL(10,2)
);

CREATE TABLE dim_customer (
 customer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 customer_name VARCHAR(50),
 city VARCHAR(30),
 state VARCHAR(30)
);

CREATE TABLE dim_date (
 date_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 full_date DATE UNIQUE,
 year INT,
 month INT,
 day INT,
 month_name VARCHAR(10)
);


CREATE TABLE sales_fact (
 sale_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 product_id INT REFERENCES dim_product(product_id),
 customer_id INT REFERENCES dim_customer(customer_id),
 date_id INT REFERENCES dim_date(date_id),
 quantity INT,
 amount DECIMAL(10,2)
);


INSERT INTO dim_product (product_name, category, price) VALUES
('Laptop', 'Electronics', 75000.00),
('Phone', 'Electronics', 45000.00),
('Notebook', 'Stationery', 50.00),
('Desk Chair', 'Furniture', 12000.00);

INSERT INTO dim_customer (customer_name, city, state) VALUES
('Alice', 'Chennai', 'Tamil Nadu'),
('Bob', 'Mumbai', 'Maharashtra'),
('Charlie', 'Delhi', 'Delhi'),
('Diana', 'Bangalore', 'Karnataka');

INSERT INTO dim_date (full_date, year, month, day, month_name) VALUES
('2026-01-15', 2026, 1, 15, 'January'),
('2026-02-10', 2026, 2, 10, 'February'),
('2026-03-05', 2026, 3, 5, 'March'),
('2026-04-20', 2026, 4, 20, 'April');


INSERT INTO sales_fact (product_id, customer_id, date_id, quantity, amount) VALUES
(1, 1, 1, 2, 150000.00),
(2, 2, 2, 3, 135000.00),
(3, 3, 3, 10, 500.00),
(4, 4, 4, 1, 12000.00),
(1, 3, 4, 1, 75000.00);


SELECT
 d.full_date,
 d.month_name,
 p.product_name,
 p.category,
 c.customer_name,
 c.city,
 s.quantity,
 s.amount
FROM sales_fact s
JOIN dim_product p ON s.product_id = p.product_id
JOIN dim_customer c ON s.customer_id = c.customer_id
JOIN dim_date d ON s.date_id = d.date_id
ORDER BY d.full_date, p.product_name;

